# generated by datamodel-codegen:
#   filename:  models.yaml
#   timestamp: 2023-03-31T16:43:27+00:00

from __future__ import annotations

from typing import Any, Optional

from pydantic import BaseModel, Field


class AnimalObservation(BaseModel):
    methaneyield: Optional[Any] = Field(None, description='Methane (x / d)')
    net_energy_requirement: Optional[float] = Field(
        None, description='http://opendata.inrae.fr/ATOL/page/ATOL_0001601'
    )
    observedAt: Optional[str] = None
    observationDate: Optional[str] = Field(None, description='Date of the observation')


class HarvestEvent(BaseModel):
    harv_operat_main_product: Optional[Any] = Field(
        None, description='Harvest operations, percent economic product harvested'
    )
    harv_operat_size_categor: Optional[Any] = Field(
        None, description='Harvest operations size category'
    )
    harv_operation_byproduct: Optional[Any] = Field(
        None, description='Harvest operations, percent of by-product harvested'
    )
    harvest_amount: Optional[Any] = Field(
        None, description='Harvest, total amount removed as mass'
    )
    harvest_area: Optional[Any] = Field(None, description='Harvest area')
    harvest_crop: Optional[Any] = Field(
        None, description='Harvest operations, crop harvested'
    )
    harvest_cut_height: Optional[Any] = Field(
        None, description='Harvest, height of cut'
    )
    harvest_method: Optional[Any] = Field(None, description='Harvest method')
    harvest_operat_component: Optional[Any] = Field(
        None, description='Harvest operations, crop component harvested'
    )
    harvest_operations_date: Optional[Any] = Field(
        None, description='Harvest operations date, DAP if year = -99'
    )
    harvest_operations_day: Optional[Any] = Field(
        None, description='Harvest operations day, DAP if year = -99'
    )
    harvest_operations_level: Optional[Any] = Field(
        None, description='Harvest operations level, links to HARVEST table'
    )
    harvest_operations_year: Optional[Any] = Field(
        None, description='Harvest operations year'
    )
    harvest_stage: Optional[Any] = Field(
        None, description='Harvest, growth stage of crop at date'
    )
    id: Optional[Any] = Field(None, description='id')


class AnimalDailyObserved(AnimalObservation):
    pass


class HarvestEvent1(HarvestEvent):
    pass
