---
components:
  schemas:
    Animal:
      $ref: ./models/AnimalModels.yaml#/Animal
    AnimalDailyObs:
      $ref: ./models/AnimalModels.yaml#/AnimalDaily
    AnimalDailyPred:
      $ref: ./models/AnimalModels.yaml#/AnimalDaily
    Feed:
      $ref: ./models/AnimalModels.yaml#/Feed

info:
  description: Model Definitions for INTEGRITY research project
  title: INTEGRITY livestock models schema
  version: 0.0.1
openapi: 3.0.0
paths: {}
