---
components:
  schemas:
    Herd:
      x-ngsi:
        uri-prefix: https://integrity.github.io
      properties:
        herdid:
          description: ID of the herd
        name:
          description: Name of the herd
    Animal:
      $ref: ./templates/animals.yaml#/Animal
    AnimalDaily:
      $ref: ./templates/animals.yaml#/AnimalDaily
    Feed:
      $ref: ./templates/animals.yaml#/Feed

info:
  description: Model Definitions for INTEGRITY research project
  title: INTEGRITY livestock models schema
  version: 0.0.1
openapi: 3.0.0
paths: {}
